#!/usr/bin/env node
'use strict'

const fs = require('fs')
const chalk = require('chalk')
const assert = require('assert')

mustExist('build/webpack.stats.json')
mustExist('build/pages/index.html')
mustExist('build/pages/docs/index.html')
mustExist('build/pages/pancake/index.html')

console.log(chalk.bold.green('* Tests passed.'))

function mustExist (path) {
  console.log('* Checking that %s exists.', path)
  assert(fs.existsSync(path), path + ' must exist')
}
